#!/usr/bin/env bash
#
# Wazo DHCP Tenant Generator
#
# Generate an ISC DHCP subnet configuration for a Wazo tenant/site.
#
# The generated configuration keeps the Wazo/phone-class behavior from the
# original script while making the paths and phone classes configurable.
#

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

DHCP_SITES_DIR="${DHCP_SITES_DIR:-/etc/dhcp/dhcpd_sites}"
DHCP_EXTRA_FILE="${DHCP_EXTRA_FILE:-/etc/dhcp/dhcpd_extra.conf}"
DHCP_SERVICE="${DHCP_SERVICE:-isc-dhcp-server}"
PHONE_CLASSES_FILE="${PHONE_CLASSES_FILE:-${SCRIPT_DIR}/config/phone-classes.conf}"
BACKUP_TIMESTAMP="$(date +%Y%m%d_%H%M%S)"

die() {
    echo "ERROR: $*" >&2
    exit 1
}

validate_ipv4() {
    local ip="$1"
    local o1 o2 o3 o4

    [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]] || return 1

    IFS='.' read -r o1 o2 o3 o4 <<< "$ip"

    for octet in "$o1" "$o2" "$o3" "$o4"; do
        (( octet >= 0 && octet <= 255 )) || return 1
    done

    return 0
}

validate_site_name() {
    local name="$1"
    [[ "$name" =~ ^[A-Za-z0-9._-]+$ ]]
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Command not found: $1"
}

prompt_ipv4() {
    local prompt="$1"
    local default="${2:-}"
    local value

    while true; do
        if [[ -n "$default" ]]; then
            read -r -p "$prompt [$default] : " value
            value="${value:-$default}"
        else
            read -r -p "$prompt : " value
        fi

        if validate_ipv4 "$value"; then
            printf '%s' "$value"
            return 0
        fi

        echo "IPv4 invalide."
    done
}

ensure_directories() {
    mkdir -p "$DHCP_SITES_DIR"
    [[ -f "$DHCP_EXTRA_FILE" ]] || touch "$DHCP_EXTRA_FILE"
}

load_phone_classes() {
    [[ -f "$PHONE_CLASSES_FILE" ]] ||
        die "Phone classes file not found: $PHONE_CLASSES_FILE"

    PHONE_CLASS_LINES=()

    while IFS= read -r line || [[ -n "$line" ]]; do
        [[ -z "$line" ]] && continue
        [[ "$line" =~ ^[[:space:]]*# ]] && continue
        PHONE_CLASS_LINES+=("$line")
    done < "$PHONE_CLASSES_FILE"
}

generate_dhcp_file() {
    cat > "$TARGET_FILE" <<EOF
# This file has been automatically generated by wazo-dhcp-tenant-generator.
# Do not edit manually; regenerate it with the script instead.
#
# Site: $SITE_NAME
# Generated: $(date --iso-8601=seconds)

# Declaration for subnet
subnet $SUBNET netmask $MASK {
    authoritative;

    option subnet-mask $MASK;
    option routers $ROUTER_IP;

    pool {
        log(concat("[", binary-to-ascii(16, 8, ":", hardware), "] POOL VoIP $SITE_NAME"));

        range $RANGE_START_IP $RANGE_END_IP;

        on commit {
            execute("dxtorc",
                    "commit",
                    binary-to-ascii(10, 8, ".", leased-address),
                    binary-to-ascii(16, 8, ":", suffix(hardware, 6)),
                    pick-first-value(concat("060", binary-to-ascii(16, 8, ".", option vendor-class-identifier)), "")
                   );
        }

        ### Assign who is going to use this pool
$(printf '        allow members of "%s";\n' "${PHONE_CLASS_LINES[@]}")
    }
}
EOF

    echo "Fichier généré : $TARGET_FILE"
}

update_extra_file() {
    INCLUDE_LINE="include \"$TARGET_FILE\";"

    if grep -Fqx "$INCLUDE_LINE" "$DHCP_EXTRA_FILE"; then
        echo "L'inclusion existe déjà dans $DHCP_EXTRA_FILE"
        return
    fi

    printf '%s\n' "$INCLUDE_LINE" >> "$DHCP_EXTRA_FILE"
    echo "Ajouté dans $DHCP_EXTRA_FILE"
}

backup_existing_file() {
    local backup

    backup="${TARGET_FILE}.bak_${BACKUP_TIMESTAMP}"
    cp -- "$TARGET_FILE" "$backup"
    echo "Sauvegarde effectuée : $backup"
}

handle_existing_file() {
    [[ -f "$TARGET_FILE" ]] || return 0

    echo
    echo "ATTENTION : le fichier $TARGET_FILE existe déjà."
    echo "Que veux-tu faire ?"
    echo "  1) Écraser le fichier"
    echo "  2) Annuler"
    echo "  3) Sauvegarder l'ancien fichier puis remplacer"

    local choice
    read -r -p "Choix [1/2/3] : " choice

    case "$choice" in
        1)
            echo " > Écrasement du fichier existant."
            ;;
        2)
            echo " > Annulation."
            exit 0
            ;;
        3)
            backup_existing_file
            ;;
        *)
            die "Choix invalide."
            ;;
    esac
}

validate_dhcp_configuration() {
    echo "Test de la configuration DHCP..."

    if ! dhcpd -t; then
        die "Erreur dans la configuration DHCP. Le service ne sera pas redémarré."
    fi
}

restart_dhcp_service() {
    echo "Redémarrage du service DHCP : $DHCP_SERVICE"

    if systemctl restart "$DHCP_SERVICE"; then
        echo "Service redémarré avec succès."
    else
        die "Erreur lors du redémarrage du service DHCP. Consultez les logs."
    fi
}

main() {
    echo "==============================================="
    echo " Wazo DHCP Tenant Generator"
    echo "==============================================="

    require_command dhcpd
    require_command systemctl
    require_command grep
    require_command cp

    if [[ "${EUID}" -ne 0 ]]; then
        die "Ce script doit être exécuté avec les privilèges root."
    fi

    read -r -p "Nom du site/tenant (sans espace) : " SITE_NAME
    while [[ -z "$SITE_NAME" ]] || ! validate_site_name "$SITE_NAME"; do
        echo "Nom invalide. Utilise uniquement : lettres, chiffres, '.', '_' ou '-'."
        read -r -p "Nom du site/tenant (sans espace) : " SITE_NAME
    done

    SUBNET="$(prompt_ipv4 "Sous-réseau (ex: 10.X.Y.0)")"

    IFS='.' read -r A X Y Z <<< "$SUBNET"
    if [[ "$A" != "10" ]]; then
        die "Le sous-réseau doit commencer par 10.X.Y.0."
    fi

    MASK="$(prompt_ipv4 "Masque" "255.255.255.0")"
    RANGE_START_IP="$(prompt_ipv4 "Début de plage DHCP (IPv4 complète)")"
    RANGE_END_IP="$(prompt_ipv4 "Fin de plage DHCP (IPv4 complète)")"
    ROUTER_IP="$(prompt_ipv4 "Routeur (IPv4 complète)")"

    DHCP_SITES_DIR="${DHCP_SITES_DIR%/}"
    TARGET_FILE="${DHCP_SITES_DIR}/dhcpd_${SITE_NAME}.conf"

    ensure_directories
    load_phone_classes
    handle_existing_file
    generate_dhcp_file
    update_extra_file

    validate_dhcp_configuration
    restart_dhcp_service

    echo
    echo "=== Terminé ==="
}

main "$@"
